id: P004126
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:54:53.396081
source_metadata:
  id: bdr:W1AC43
  title: དབུ་མའི་སྤྱི་དོན་ཟབ་དོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    8f5c4c294c5e4d3db6cde20b69870ab3:
      image_group_id: I2PD18528
      title: ''
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
