id: I7C10B83B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:17:22+00:00'
last_modified: '2022-06-07T20:25:32.059370+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC43
  title: དབུ་མའི་སྤྱི་དོན་ཟབ་དོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0578:
      image_group_id: I2PD18528
      title: ''
      total_pages: 372
      order: 1
      base_file: 0578.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
